"""empty message

Revision ID: 0b241e38b212
Revises: c3524f5c45ef
Create Date: 2020-06-17 21:06:21.063551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b241e38b212'
down_revision = 'c3524f5c45ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_date_time', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created_date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_date_time')
    op.drop_column('Artist', 'created_date_time')
    # ### end Alembic commands ###
