"""empty message

Revision ID: 0bc819ed6f20
Revises: 1b4f0aede687
Create Date: 2020-06-12 10:45:20.871225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc819ed6f20'
down_revision = '1b4f0aede687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    # ### end Alembic commands ###
