"""empty message

Revision ID: 41341cc8c5b5
Revises: c4f5ba63225f
Create Date: 2020-06-15 11:21:31.983097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41341cc8c5b5'
down_revision = 'c4f5ba63225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=100), nullable=True))
    op.add_column('Venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_venue')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
