"""empty message

Revision ID: 50353cd8c172
Revises: a11dd91898c7
Create Date: 2020-06-15 13:09:52.754518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50353cd8c172'
down_revision = 'a11dd91898c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
