"""empty message

Revision ID: 538cade41d3b
Revises: 96ef3dda4f39
Create Date: 2020-06-12 15:43:12.553730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538cade41d3b'
down_revision = '96ef3dda4f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Venue_artist_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_artist_id_fkey', 'Venue', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
