"""empty message

Revision ID: 633822a71bf6
Revises: ec0f39dbf01b
Create Date: 2020-06-12 11:21:42.113345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633822a71bf6'
down_revision = 'ec0f39dbf01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'show_id')
    # ### end Alembic commands ###
