"""empty message

Revision ID: 9f0a8b3eb30f
Revises: 412f5bd2d795
Create Date: 2020-06-15 11:25:49.017978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0a8b3eb30f'
down_revision = '412f5bd2d795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'show_time')
    # ### end Alembic commands ###
